[package]
name = "scheduler2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substrait = "0.21.0"
tonic = "0.11.0"
tokio = "1.36.0"

[build-dependencies]
tonic-build = "0.11"
