[data]
    path = "./test_files/"

[scheduler]
    id_addr = "0.0.0.0"
    port = 15721

[[executors]]
    id = 1
    ip_addr = "0.0.0.0"
    port = 12345
    numa_node = 0

[[executors]]
    id = 2
    ip_addr = "0.0.0.0"
    port = 65533
    numa_node = 1
